### PR TITLE
Fix-86

### PR DESCRIPTION
**Pull request by DEEPA-CHERI**
Add solution in java

### CODE REVIEW

**Comment by DEEPA-CHERI** [comment]
I'm new to opensource contribution,  Just tried doing this one. And please also help adding the label hacktoberfest to the issue if this adds value to the repository.

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Rename the file ```AddTwoNumber.java``` to ```2. Add Two Numbers.java```

**Comment by DEEPA-CHERI** [comment]
Addressed review comments.

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
remove or comment out this class.
```java
public class ListNode {
    int val;
    ListNode next;

    ListNode() {
    }

    ListNode(int val) {
        this.val = val;
    }

    ListNode(int val, ListNode next) {
        this.val = val;
        this.next = next;
    }
}
```

**Comment by DEEPA-CHERI** [comment]
Addressed the latest review comment

**Review by md-shamim-ahmad — APPROVED** [review]

**Comment by md-shamim-ahmad** [comment]
Awesome.
Thanks for your contribution :)

**Pull request merged**
