### PR TITLE
Create SingleNumber.cpp

### PR DESCRIPTION
**Pull request by Anubhav-Ghosh1**

### CODE REVIEW

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Thanks for your contribution.
Please use a meaningful name for the function and variable name and format your code by clang-format rules.
And rename the folder name by the original name of the problem and file name also  and add a ```README.md``` file following this [guidelines](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidlines/How%20to%20Add%20LeetCode%20Question.md)

**Comment by Anubhav-Ghosh1** [comment]
> Thanks for your contribution. Please use a meaningful name for the function and variable name and format your code by clang-format rules. And rename the folder name by the original name of the problem and file name also and add a `README.md` file following this [guidelines](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidlines/How%20to%20Add%20LeetCode%20Question.md)

I have made the changes to the code and I'll be make an seperate pr request and add an read.md file for the same as this request is accepted.

**Comment by md-shamim-ahmad** [comment]
It will be good if you create the ```readme.md``` file into this same PR.

**Comment by Anubhav-Ghosh1** [comment]
I have create and new pr with other contribution have a look please

**Pull request closed without merging**
