### PR TITLE
Java solution to 704. Binary Search

### PR DESCRIPTION
**Pull request by satvikydv**

### CODE REVIEW

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Thanks for your contribution.
Please use a meaningful name for the function and variable name and format your code by clang-format rules.
And rename the file name ```Binary Search.cpp``` to  ```704. Binary Search.cpp``` and add a ```README.md``` file following this [guidelines](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidlines/How%20to%20Add%20LeetCode%20Question.md)

**Comment by satvikydv** [comment]
I have made the requested changes. Please check and let me know if something else is required.

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Your code looks good. But does not follow ```Clang-Format```.
Please format your code.

**Comment by satvikydv** [comment]
Please review @md-shamim-ahmad

**Review by md-shamim-ahmad — APPROVED** [review]

**Pull request merged**
