### PR TITLE
Create Two Sum.cs

### PR DESCRIPTION
**Pull request by NickzArora**
Created Two Sum Solution in c#,
 Time Complexity - O(n)
 Space Complexity - O(n)

- [x] I have read [CONTRIBUTING.md](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All functions and variable names follow **Clean Code** naming conventions.
- [ ] This code follows the clang-format style.

### CODE REVIEW

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Remove these line from the code
We don't need extra unnecessary information
```cpp        
        /// <summary>
        /// Finds the first Pair of numbers that sum upto the sum provided
        /// </summary>
        /// <param name="arr">Array</param>
        /// <param name="sum">Sum of a Pair of Numbers</param>
        /// <exception cref="ArgumentException"></exception>
```

**Comment by md-shamim-ahmad** [comment]
@NickzArora Hey notice
I didn't tell you to delete all comments.
[see here](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/pull/92#pullrequestreview-1659444654)

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
rename the file ```Two Sum.cs``` to ```1. Two Sum.cs```

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
remove **main** function from this code

**Comment by NickzArora** [comment]
@md-shamim-ahmad All comments are addressed.

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Hey please add the code you submit to leetcode for acceptance testing but use ```clang-format``` these codes before adding.

**Comment by NickzArora** [comment]
@md-shamim-ahmad I have updated the code with the my solution submitted to leetcode, I couldn't find clang-formatter for c#.

**Review by md-shamim-ahmad — APPROVED** [review]
Awesome.
Now, your code is working fine.
Thanks for your contribution.

**Pull request merged**
