### PR TITLE
Adding Solutions to 102.Binary Tree Level Order Traversal and 141.Linked List Cycle

### PR DESCRIPTION
**Pull request by Vineetttt**

### CODE REVIEW

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Hey thanks for your pull request
Your code looks good.
Please rename the file name ```“Binary Tree Level Order Traversal.java”``` to ```“102. Binary Tree Level Order Traversal.java”```.

**Comment by Vineetttt** [comment]
@md-shamim-ahmad yes thats done, check now

**Comment by md-shamim-ahmad** [comment]
You are so fast :)
and rename this file please
```“Readme.md”``` to ```“README.md”```

**Comment by Vineetttt** [comment]
haha, I was online so did it :)

**Review by md-shamim-ahmad — APPROVED** [review]

**Comment by md-shamim-ahmad** [comment]
Thanks for your contribution :)

**Pull request merged**
