### PR TITLE
Fixes #84

### LINKED ISSUE #84: Add solutions for 207. Course Schedule and 347. Top K Frequent Elements
Add solutions for problems:- 
207. Course Schedule
347. Top K Frequent Elements

### PR DESCRIPTION
**Pull request by Anonymous5164**
Fixes #84

### CODE REVIEW

**Comment by Anonymous5164** [comment]
Kindly review my PR and let me know if any changes are needed

**Comment by md-shamim-ahmad** [comment]
solve these [problem](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/pull/85/files/b406ccd2df5b24e5cca77e59c41949c295d227bd)

**Comment by Anonymous5164** [comment]
Can you please elaborate the changes to be made in PR, as in I have solved both the problems for which I have raised the issue, also added README.md.

**Comment by Anonymous5164** [comment]
Just resolved conflict which was there, let me know if any further changes are needed

**Comment by md-shamim-ahmad** [comment]
correct ```README.md``` file for all commit

**Comment by Anonymous5164** [comment]
I havent made any changes to README.md in any commit, can you please elaborate what to fix in README.md, because havent noticed anything wrong with .md files

**Pull request closed without merging**
