### PR TITLE
added leetcode 14 java soln

### LINKED ISSUE #101: Leetcode 14. Longest common prefix java solution missing
### Which problem do you want to solve?

I want to add java solution to the leetcode 14 Longest common prefix

### Input and Output details

The LeetCode problem "Longest Common Prefix" (problem number 14) asks you to find the longest common prefix among an array of strings. You are given an array of strings, and you need to find the longest string that is a prefix of all the strings in the array.

Here are the input and output details for this problem:

Input:

An array of strings, strs, where 0 <= strs.length <= 200 and 0 <= strs[i].length <= 200.
The input strings consist of only lowercase and uppercase English letters.
Output:

A string, which is the longest common prefix of all the strings in the input array strs.
If there is no common prefix among the input strings, return an empty string ("").

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by okaydivyansh**
closes #101 
- [x] I have read [CONTRIBUTING.md](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidelines/How%20to%20Add%20a%20new%20Solution%20Code.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All functions and variable names follow **Clean Code** naming conventions.
- [x] This code follows the clang-format style.

### CODE REVIEW

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Your solution code size is too long.
Do you have any plans to reduce the size of this code?

**Comment by okaydivyansh** [comment]
> Your solution code size is too long. Do you have any plans to reduce the size of this code?

the solution is correct. Obviously, I can reduce it but the C++ solution for the same question was kind of similar in length. I can reduce it but this solution is easy to understand and cleanly written with multiple functions for each task

**Comment by okaydivyansh** [comment]
Hi @md-shamim-ahmad I have changed the solution completely. It is very precise now. Please check

**Review by okaydivyansh — COMMENTED** [review]
#101 closes

**Review by md-shamim-ahmad — APPROVED** [review]

**Pull request merged**
