### PR TITLE
Create 4374. 4 sum problem

### PR DESCRIPTION
**Pull request by abhichauhan824**

### CODE REVIEW

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
hi,
move this solution code into correct path.
create a sub folder name ```18. 4Sum``` into ```1 to 100``` folder and move your code in there.

**Review by md-shamim-ahmad — CHANGES_REQUESTED** [review]
Rename the class name as solution
and remove the main function

**Review by md-shamim-ahmad — COMMENTED** [review]
I will request you to read the [Contribution Guidelines](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/blob/main/Contribution%20Guidlines/How%20to%20Add%20a%20new%20Solution%20Code.md)

**Comment by abhichauhan824** [comment]
Actually i am new on github . i don't know to create a folder or subfolder
so that why i do some mistake

**Pull request closed without merging**
