### PR TITLE
41. First missing positive Solution Code in Java

### PR DESCRIPTION
**Pull request by vivekrawat21**
issue#78
please  add tag for hacktoberfest before merging

### CODE REVIEW

**Comment by vivekrawat21** [comment]
why it is not merging what i did wrong?

**Comment by md-shamim-ahmad** [comment]
Your code does not follow ```clang-format``` style.

And also rename the file ```First Missing Positive.java``` to ```41. First Missing Positive.java```

**Comment by vivekrawat21** [comment]
how can i i fix this?

**Comment by md-shamim-ahmad** [comment]
> how can i i fix this?

check the build details

**Review by md-shamim-ahmad — APPROVED** [review]

**Pull request merged**
